mode: "deployment"
config:
  exporters:
    otlp:
      endpoint: 10.2.0.224:4317 # `jaeger-collector` is the K8s service name. nodeport of 4317
      tls:
        insecure: true
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  service:
    pipelines:
      traces:
        exporters:
          - otlp
        processors:
          - batch
        receivers:
          - otlp