replicaCount: 1

image:
  repository: shn27/restaurant-management-system-monitoring
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASSWORD: "password"
  DB_NAME: "food_delivery"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  OTEL_EXPORTER_OTLP_ENDPOINT: "opentelemetry-kube-stack-gateway-collector.monitoring.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "go-api"
  OTEL_EXPORTER_OTLP_INSECURE: "true"