apiVersion: v1
kind: Service
metadata:
  name: jaeger-clickhouse
  namespace: observability
spec:
  selector:
    clickhouse.altinity.com/chi: jaeger-clickhouse # This selector targets the pods created by the ClickHouseInstallation CR
  ports:
    - name: native
      port: 9000
      targetPort: 9000 # The default port for ClickHouse's native protocol