apiVersion: v1
kind: Service
metadata:
  name: jaeger-clickhouse-collector-lb
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: collector
  ports:
    - name: grpc
      port: 14250
      targetPort: 14250
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
