apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-collector-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"  # tells NGINX this is gRPC
spec:
  rules:
    - host: jaeger.sohan.ace   # your external DNS
      http:
        paths:
          - path: /sample
            pathType: Prefix
            backend:
              service:
                name: jaeger-collector
                port:
                  number: 4317